#!/bin/sh

export TOASTER_ORG_NAME="Your Organization"
export TOASTER_HOSTNAME="mail.example.com"
export TOASTER_MAIL_DOMAIN="example.com"
export TOASTER_ADMIN_EMAIL="postmaster@example.com"
export TOASTER_SRC_URL="https://raw.githubusercontent.com/msimerson/Mail-Toaster-6/master"

# If your hosts public facing IP(s) are not bound to a local interface, configure it here.
# Haraka determines it at runtime (with STUN) but the DNS configuration cannot
export PUBLIC_IP4=""
export PUBLIC_IP6=""

export JAIL_NET_PREFIX="172.16.15"
export JAIL_NET_MASK="/19"
export JAIL_NET_INTERFACE="lo1"
export JAIL_NET6="fd7a:e5cd:1fc1:xxxx:xxxx:xxxx:xxxx"
export ZFS_VOL="zroot"
export ZFS_JAIL_MNT="/jails"
export ZFS_DATA_MNT="/data"
export TOASTER_EDITOR="vim-tiny"
export TOASTER_MSA="haraka"
export TOASTER_MYSQL="1"
export TOASTER_MYSQL_PASS=""
export TOASTER_NRPE=""
export TOASTER_PKG_AUDIT="0"
export TOASTER_PKG_BRANCH="latest"
export TOASTER_USE_TMPFS="0"
export TOASTER_VPOPMAIL_CLEAR="1"
export TOASTER_VPOPMAIL_EXT="0"
export CLAMAV_FANGFRISCH="0"
export MAXMIND_LICENSE_KEY=""
export ROUNDCUBE_SQL="0"
export ROUNDCUBE_DEFAULT_HOST=""
export ROUNDCUBE_PRODUCT_NAME="Roundcube Webmail"
export ROUNDCUBE_ATTACHMENT_SIZE_MB="25"

export WILDDUCK_MAIL_DOMAIN="example.com"
export WILDDUCK_HOSTNAME="mail.example.com"
export WILDDUCK_MONGO_DSN="mongodb://wildduck:emailWantsQuackers@172.16.15.45:27017/wildduck?authSource=admin"
export ZONEMTA_MONGO_DSN="mongodb://zone-mta:ktoBt20Nmo90to@172.16.15.45:27017/zone-mta?authSource=admin"
